version: '3'

services:
  ip_notify:
    build: 
      context: .
      network: host
    container_name: ip_notify

    volumes:
      - ./data:/data
    environment:
      # The discord webhook url. Include here or in .env file
      - WEBHOOK_URL=${WEBHOOK_URL}
      # The color of the Discord Embed in hex
      - EMBED_COLOR=1bb106
      # The link when clicking the Embed author
      - AUTHOR_URL=https://github.com/jack-mil
      # The icon for the Embed and User avatar
      - ICON_URL=https://1.1.1.1/favicon.ico
      # The file (in the container) to store the previous ip
      - IP_CACHE=/data/ip.txt
      # An additional log file (in the container)
      - LOG_FILE=/data/logs.txt
      # Time Zone for logs
      - TZ=America/New_York
    dns: 1.1.1.1